version: '3'

services:
  db:
    image: mariadb
    container_name: db
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - net
  client:
    build:
      context: ./client
      dockerfile: dev.dockerfile
    container_name: client
    ports:
      - '3000:3000'
    volumes: [ './client/src:/app/src' ]
  server:
    build:
      context: ./server
      dockerfile: dev.dockerfile
    container_name: server
    ports:
      - '4000:4000'
    volumes: [ './server/src:/app/src', './server/tmp/:/tmp/files' ]
    networks:
      - net
  pdf_api:
    build: ./services/pdf_api
    container_name: pdf_api
    ports:
      - '8000:8000'
    restart: always
    networks:
      - net
networks:
  net:
volumes:
  db:


